In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [11]:
df2 = pd.read_csv("/content/data_part_10.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/data_part_10.csv'

In [558]:
df2.shape

(5062, 8)

In [559]:
df2.head()

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam
1,tt4339526,Aavas,2016 Video,-,-,-,"Music, Romance",nepali
2,tt4200384,Hello Hyderabad,2001,-,-,-,Drama,hindi
3,tt4947952,Time Limit 36 Hours,2004,-,-,-,Action,hindi
4,tt9614950,Thirumanam,2019,156 min,6.5,119,Drama,tamil

In [560]:
#keeping impoertant columns for recommmendation
df2 = df2[['ID','Movie Name','Year','Timing(min)','Rating(10)','Votes','Genre','Language']]

In [561]:
df2 = df2[df2['ID'] != 'tt0398974']

In [562]:
df2 = df2[df2['ID'] != 'tt1702558']

In [563]:
df2.head(2)

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam
1,tt4339526,Aavas,2016 Video,-,-,-,"Music, Romance",nepali

In [564]:
df2.shape

(5062, 8)

In [565]:
df2.isnull().sum()

ID               0
Movie Name       0
Year           158
Timing(min)      0
Rating(10)       0
Votes            0
Genre            0
Language         0
dtype: int64

In [566]:
df2.dropna(inplace=True)

In [567]:
df2.isnull().sum()

ID             0
Movie Name     0
Year           0
Timing(min)    0
Rating(10)     0
Votes          0
Genre          0
Language       0
dtype: int64

In [568]:
df2.shape

(4904, 8)

In [569]:
df2.duplicated().sum()

0

In [570]:
#handling genres

df2.iloc[0]['Genre']

'Comedy, Drama            '

In [571]:
df2.head()

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam
1,tt4339526,Aavas,2016 Video,-,-,-,"Music, Romance",nepali
2,tt4200384,Hello Hyderabad,2001,-,-,-,Drama,hindi
3,tt4947952,Time Limit 36 Hours,2004,-,-,-,Action,hindi
4,tt9614950,Thirumanam,2019,156 min,6.5,119,Drama,tamil

In [572]:
#handle keywords
df2.iloc[0]['Language']

'malayalam'

In [573]:
#handle cast
df2.iloc[0]['Year']

'2005'

In [574]:
#handle crew
df2.iloc[0]['Rating(10)']

'2.8'

In [575]:
df2.head()

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam
1,tt4339526,Aavas,2016 Video,-,-,-,"Music, Romance",nepali
2,tt4200384,Hello Hyderabad,2001,-,-,-,Drama,hindi
3,tt4947952,Time Limit 36 Hours,2004,-,-,-,Action,hindi
4,tt9614950,Thirumanam,2019,156 min,6.5,119,Drama,tamil

In [576]:
df2['tags'] = df2['Year'] + df2['Genre'] + df2['Language'] + df2['Votes'] + df2['Rating(10)']

In [577]:
df2.head()

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language,tags
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam,"2005Comedy, Drama malayalam842.8"
1,tt4339526,Aavas,2016 Video,-,-,-,"Music, Romance",nepali,"2016 VideoMusic, Romance nepali--"
2,tt4200384,Hello Hyderabad,2001,-,-,-,Drama,hindi,2001Drama hindi--
3,tt4947952,Time Limit 36 Hours,2004,-,-,-,Action,hindi,2004Action hindi--
4,tt9614950,Thirumanam,2019,156 min,6.5,119,Drama,tamil,2019Drama tamil1196.5

In [578]:
df2.iloc[0]['tags']

'2005Comedy, Drama            malayalam842.8'

In [579]:
new_df = df2[['Movie Name','ID']]
new_df['tags'] = df2['tags'] # Add this line to copy the 'tags' column
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))
new_df.head()

<ipython-input-579-78305ad17b58>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = df2['tags'] # Add this line to copy the 'tags' column
<ipython-input-579-78305ad17b58>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

,Movie Name,ID,tags
0,Junior Senior,tt0827770,"2 0 0 5 C o m e d y , D r a m a ..."
1,Aavas,tt4339526,"2 0 1 6 V i d e o M u s i c , R o m a n c ..."
2,Hello Hyderabad,tt4200384,2 0 0 1 D r a m a h i ...
3,Time Limit 36 Hours,tt4947952,2 0 0 4 A c t i o n h ...
4,Thirumanam,tt9614950,2 0 1 9 D r a m a t a ...

In [580]:
new_df = df2[['Movie Name','ID']]

In [581]:
new_df.head()

            Movie Name         ID
0        Junior Senior  tt0827770
1                Aavas  tt4339526
2      Hello Hyderabad  tt4200384
3  Time Limit 36 Hours  tt4947952
4           Thirumanam  tt9614950

In [582]:
# Create 'tags' column in df2
df2['tags'] = df2['Year'] + df2['Genre'] + df2['Language'] + df2['Votes'] + df2['Rating(10)']

# Create new_df and copy the 'tags' column from df2
new_df = df2[['Movie Name', 'ID', 'tags']].copy() # Include 'tags' in the new DataFrame
# Apply the stems function to the 'tags' column
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [583]:
import nltk
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

nltk.download('punkt') # Download punkt tokenizer if not already downloaded

ps = PorterStemmer()

def stems(text):
    T = []
    for i in text.split():
        T.append(ps.stem(i))
    return " ".join(T)

# Create 'tags' column by joining relevant text columns with spaces
df2['tags'] = df2['Genre'].astype(str) + ' ' + \
              df2['Language'].astype(str) + ' ' + \
              df2['Votes'].astype(str)

# Apply stemming to the 'tags' column
df2['tags'] = df2['tags'].apply(stems)

# Create new_df and copy the 'tags' column from df2
new_df = df2[['Movie Name', 'ID', 'tags']].copy()

# Initialize CountVectorizer with adjusted parameters
cv = CountVectorizer(max_features=5000, stop_words='english', token_pattern=r"(?u)\b\w+\b") # Adjust token_pattern

# Fit and transform the 'tags' data
vector = cv.fit_transform(new_df['tags']).toarray()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [584]:
new_df.iloc[0]['tags']

'comedy, drama malayalam 84'

In [585]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [586]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [587]:
vector[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [588]:
vector.shape

(4904, 644)

In [589]:
len(cv.get_feature_names_out()) # Use get_feature_names_out() instead of get_feature_names()

644

In [590]:
from sklearn.metrics.pairwise import cosine_similarity

In [591]:
similarity = cosine_similarity(vector)

In [592]:
similarity.shape

(4904, 4904)

In [593]:
#similarity

In [594]:
df2.head(2)

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language,tags
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam,"comedy, drama malayalam 84"
1,tt4339526,Aavas,2016 Video,-,-,-,"Music, Romance",nepali,"music, romanc nepali -"

In [595]:
def recommend(movie):
  index = new_df[new_df['Movie Name'] == movie].index[0] # Changed 'title' to 'Movie Name'
  distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
  for i in distances[1:6]:
    print(new_df.iloc[i[0]]['Movie Name']) # Changed .Movie_Name to ['Movie Name'] for consistency

In [596]:
new_df[new_df['Movie Name']== 'Aavas'].index[0]

1

In [5]:
recommend('avas')

NameError: name 'recommend' is not defined

In [598]:
df2.head(1)

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language,tags
0,tt0827770,Junior Senior,2005,-,2.8,84,"Comedy, Drama",malayalam,"comedy, drama malayalam 84"

In [599]:
#import pickle

In [600]:
import pickle
pickle.dump(new_df,open('10th_movie_list.pkl','wb'))

In [601]:
pickle.dump(similarity,open('10th_similarity.pkl','wb'))